### PR TITLE
[Feature] Next@14 + SSR + SWR + Latest Packages + Vulnerability fixes + Performance improvements

### PR DESCRIPTION
**Pull request by wiyco**
# Features

Dev. 🐧

## What does this PR do?

- Upgrade packages to latest
  - [SSRF vulnerability in Next.js](https://github.com/iputapp/lounas/pull/279) can be fixed
- Modify configuration files due to package updates
- Replace the traditional Lottie with a non-SSR (Server-Side Rendering) version
  - Including creating a non-SSR component
  - Fix the issue of `ReferenceError: document is not defined` in Node@20
- Remove the deprecated `themeColor` from the Metadata in the Root Layout
- Delete unused files (`constants.ts`, `svg.d.ts`)
- Replace `@supabase/auth-helpers-nextjs` with `@supabase/ssr`
- Correct session validation method
  - Fixing session hijacking vulnerability
- Fix the issue OTP cannot resend.
- Extend the OTP resend interval from 20 seconds to 30 seconds
  - Also updated Supabase Auth settings (Project Settings > Auth > Minimum interval between emails being sent)
- Replace client fetching using `useEffect` and Abort method with SWR
  - Enabling loading and error state checks
  - Performance improvements
- Uninstall `@supabase/auth-helpers-nextjs` package
- Update README (Add SWR Docs)
- Removed unused import statement that had been flagged by ESLint
- Fix the issue of signed-out users being able to access the home page in just after sign-out
- Fix layout issues on the Landing (Top) page (Text misalignment and non-blurring in Safari)
- Manage media links (like SNS) with constants values (enum)

## Before submitting

> [!Warning]
>
> The following is allowed for review only. (No additions or modifications are permitted.)

- [x] I have read the [Contribution Guidelines](https://github.com/PROJECT-PIPLUP/lounas/blob/develop/.github/CONTRIBUTING.md).
- [x] I agree to the [Code of Conduct](https://github.com/PROJECT-PIPLUP/lounas/blob/develop/.github/CODE_OF_CONDUCT.md).

## Remark

> [!IMPORTANT]
> There is a possibility that the issue in below will also be fixed.
> - #280 
>
> Testing is required.

### CODE REVIEW

**Review by wiyco — COMMENTED** [review]
Self ✅

**Review by HIMA-HIMAZIN — COMMENTED** [review]
確認しました。問題はありません。

**Comment by wiyco** [comment]
> [PC版ランディングページ内のInstagramリンク](https://github.com/iputapp/lounas/blob/d985553a286fa56806d6709c9392fe505240dede/src/app/(root)/page.tsx#L914)において旧ユーザー名になっている。 変更→https://www.instagram.com/iputapp

SNS等のリンクを以下の通りに修正しました。

https://github.com/iputapp/lounas/blob/907210ce6cc06eddf8a6e8441381f93b1a4d3594/src/_constants/links.ts#L1-L7

各リンクの置き換え：https://github.com/iputapp/lounas/pull/281/commits/907210ce6cc06eddf8a6e8441381f93b1a4d3594

**Review by Shvain — APPROVED** [review]
✅️

**Review by HIMA-HIMAZIN — APPROVED** [review]

**Pull request merged**
